<a href="https://colab.research.google.com/github/Jalaludin17/Pytorch/blob/main/01_Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### 01_Torch

In [ ]:
import torch
print(torch.__version__)

2.8.0+cu126


In [ ]:
#chech if GPU is available
if torch.cuda.is_available():
  print("GPU is available")
  print(f"Using Google's GPU : {torch.cuda.get_device_name(0)}")
else:
  print("GPU is not available")
#NVIDIA Tesla T4 GPU has 16 GB of GDDR6 memory.

GPU is available
Using Google's GPU : Tesla T4


### 02_Creating Tensors

In [ ]:
#tensors
a = torch.tensor([1,2,3])
print(a)

tensor([1, 2, 3])


In [ ]:
#empty tensors
empty_tensor = torch.empty(3,2)
print(empty_tensor)

tensor([[1.2744e+04, 0.0000e+00],
        [0.0000e+00, 1.5046e-36],
        [3.5237e+00, 0.0000e+00]])


In [ ]:
#zero tensors
c = torch.zeros(3,2)
print(c)

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])


In [ ]:
#ones tensor
d = torch.ones(3,2)
print(d)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])


In [ ]:
#random tensor
e = torch.rand(3,2)
print(e)

tensor([[0.7404, 0.0454],
        [0.6086, 0.7491],
        [0.8111, 0.6258]])


In [ ]:
#reproducible tensor
torch.manual_seed(42)
f = torch.rand(3,2)
print(f)

tensor([[0.8823, 0.9150],
        [0.3829, 0.9593],
        [0.3904, 0.6009]])


In [ ]:
torch.manual_seed(42) #seed will memorize it
f = torch.rand(3,2)
print(f)

tensor([[0.0043, 0.1056],
        [0.2858, 0.0270],
        [0.4716, 0.0601]])


In [ ]:
#custom tensors
g = torch.tensor([[1,2,3],[4,5,6]])
print(g)
type(g)

tensor([[1, 2, 3],
        [4, 5, 6]])


torch.Tensor

In [ ]:
#range
h = torch.range(1,5)
print(h)

tensor([1., 2., 3., 4., 5.])


/tmp/ipython-input-3736375639.py:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  h = torch.range(1,5)


In [ ]:
i = torch.arange(1,5)
print(i)

tensor([1, 2, 3, 4])


In [ ]:
j = torch.arange(1,10,2)
print(j)

tensor([1, 3, 5, 7, 9])


In [ ]:
#arange function
k = torch.arange(1,11).reshape(5,2)
print(k)

tensor([[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10]])


In [ ]:
l = torch.zeros_like(k)
print(l)

tensor([[0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0]])


In [ ]:
m = torch.ones_like(k)
print(m)

tensor([[1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1]])


In [ ]:
q = torch.empty_like(k)
print(q)

tensor([[8027140907415206688, 7018332503360695925],
        [3544945581634188140,                 113],
        [    137404887539008,           139557024],
        [2459029316100385139,        537444691509],
        [                  0,                  65]])


In [ ]:
#line space
n = torch.linspace(1,10,5)
print(n)

tensor([ 1.0000,  3.2500,  5.5000,  7.7500, 10.0000])


In [ ]:
#indentity tensor
o = torch.eye(5)
print(o)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])


In [ ]:
#custom shape and same element
p = torch.full((4,3),2)
print(p)

tensor([[2, 2, 2],
        [2, 2, 2],
        [2, 2, 2],
        [2, 2, 2]])


In [ ]:
tensor = torch.full((4,6),6)
print(tensor)

tensor([[6, 6, 6, 6, 6, 6],
        [6, 6, 6, 6, 6, 6],
        [6, 6, 6, 6, 6, 6],
        [6, 6, 6, 6, 6, 6]])


### 03_Tensor shape

In [ ]:
tensor = torch.tensor([[1,2,3],[4,5,6]])
print(tensor)

tensor([[1, 2, 3],
        [4, 5, 6]])


In [ ]:
tensor = torch.tensor([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(tensor)

tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]]])


In [ ]:
tensor.shape

torch.Size([2, 2, 3])

### 04_Tensor data types

In [ ]:
v = torch.tensor([1,2,3,4,5])
print(v)

tensor([1, 2, 3, 4, 5])


In [ ]:
v.dtype

torch.int64

In [ ]:
x = torch.tensor([[1,2,3],[5,6,7]], dtype=torch.float32)
print(x)

tensor([[1., 2., 3.],
        [5., 6., 7.]])


In [ ]:
y = torch.rand_like(x)
print(y)

tensor([[0.2666, 0.6274, 0.2696],
        [0.4414, 0.2969, 0.8317]])


In [ ]:
y.dtype

torch.float32

In [ ]:
y.to(torch.int32)

tensor([[0, 0, 0],
        [0, 0, 0]], dtype=torch.int32)

In [ ]:
y.dtype

torch.float32

### 05_Mathematical operations

In [ ]:
tensor = torch.tensor([[1,2,3,4],[5,6,7,8]])
print(tensor)

tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])


In [ ]:
tensor.to(torch.int32)

tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]], dtype=torch.int32)

In [ ]:
sum = tensor + 2
print(sum)

tensor([[ 3,  4,  5,  6],
        [ 7,  8,  9, 10]])


In [ ]:
sub = tensor - 1
print(sub)

tensor([[0, 1, 2, 3],
        [4, 5, 6, 7]])


In [ ]:
mul = tensor * 2
print(mul)

tensor([[ 2,  4,  6,  8],
        [10, 12, 14, 16]])


In [ ]:
div = tensor/3
print(div)

tensor([[0.3333, 0.6667, 1.0000, 1.3333],
        [1.6667, 2.0000, 2.3333, 2.6667]])


In [ ]:
int_div = tensor//2
print(int_div)

tensor([[0, 1, 1, 2],
        [2, 3, 3, 4]])


In [ ]:
mode = tensor%2
print(mode)

tensor([[1, 0, 1, 0],
        [1, 0, 1, 0]])


In [ ]:
pow = tensor**2
print(pow)

tensor([[ 1,  4,  9, 16],
        [25, 36, 49, 64]])


### 06_Mathematical Operations on two tensors

In [ ]:
#Creating two new tensors
tensor1 = torch.rand(4,3)
tensor2 = torch.rand(4,3)
print(tensor1)
print(tensor2)

tensor([[0.7719, 0.7437, 0.5944],
        [0.8879, 0.4510, 0.7995],
        [0.1498, 0.4015, 0.0542],
        [0.4594, 0.1756, 0.9492]])
tensor([[0.8473, 0.8749, 0.6483],
        [0.2148, 0.9493, 0.0121],
        [0.1809, 0.1877, 0.2927],
        [0.5997, 0.1213, 0.1148]])


In [ ]:
sum = tensor1 + tensor2
print(sum)

tensor([[1.6192, 1.6186, 1.2427],
        [1.1026, 1.4003, 0.8116],
        [0.3307, 0.5892, 0.3469],
        [1.0591, 0.2969, 1.0640]])


In [ ]:
tensor3 = torch.tensor([[1.2,-2.5,-3.4],[4.6,-5.7,6.7]])
print(tensor3)

tensor([[ 1.2000, -2.5000, -3.4000],
        [ 4.6000, -5.7000,  6.7000]])


In [ ]:
#Absolute value
torch.abs(tensor3)

tensor([[1.2000, 2.5000, 3.4000],
        [4.6000, 5.7000, 6.7000]])

In [ ]:
#Round of
torch.round(tensor3)

tensor([[ 1., -2., -3.],
        [ 5., -6.,  7.]])

In [ ]:
#Ceil : round of to next integer
torch.ceil(tensor3)

tensor([[ 2., -2., -3.],
        [ 5., -5.,  7.]])

In [ ]:
# floor : round of to previous term
torch.floor(tensor3)

tensor([[ 1., -3., -4.],
        [ 4., -6.,  6.]])

In [ ]:
#Clamp : to bring all elements of the tensor in a range
torch.clamp(tensor3, min=-0.5, max=0.5)

tensor([[ 0.5000, -0.5000, -0.5000],
        [ 0.5000, -0.5000,  0.5000]])

### 07_Statistical Operations

In [ ]:
#sum of the tensor
torch.sum(tensor3)

tensor(0.9000)