<a href="https://colab.research.google.com/github/Jalaludin17/Pytorch/blob/main/02_Autograde.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch

In [ ]:
#if y = x^2
#then dy/dx = 2x

In [ ]:
x = torch.tensor(3.0, requires_grad=True)
y = x**2
print(x)
print(y)

tensor(3., requires_grad=True)
tensor(9., grad_fn=<PowBackward0>)


In [ ]:
#calculates derivative or gradients backward
y.backward()

In [ ]:
x.grad

tensor(6.)

### Derivative of chain

In [ ]:
#now y = x^2 and z = sin(y)
x = torch.tensor(3.0, requires_grad=True)
y = x**2
z = torch.sin(y)
print(x)
print(y)
print(z)

In [ ]:
#without tensor
import math
def dz_dx(x):
  return 2 * x * math.cos(x**2)

In [ ]:
dz_dx(3)

-5.466781571308061

In [ ]:
#with tensor
#will calculate derivatives with chain rule as dy/dx dz/dy and dz/dx
z.backward()

In [ ]:
x.grad

tensor(-5.4668)

### Derivatives of Simple neuron

In [ ]:
#equation for z = b + w1x1
#equation for y(pred) = sigmoid(z) = 1 / 1 - e^-z
#equation for L = [y_target.ln(y_pred) + (1 - y_target).ln(1 - y_pred)]

#we need dL/dw = dL/dy * dy/dz * dz/dw
#and dL/db = dL/dy * dy/dz * dz/db

In [ ]:
x = torch.tensor(6.7)
y = torch.tensor(0.0)
w = torch.tensor(1.0)
b = torch.tensor(0.0)

In [ ]:
# Binary Cross-Entropy Loss for scalar
def binary_cross_entropy_loss(prediction, target):
    epsilon = 1e-8  # To prevent log(0)
    prediction = torch.clamp(prediction, epsilon, 1 - epsilon)
    return -(target * torch.log(prediction) + (1 - target) * torch.log(1 - prediction))

In [ ]:
# Forward pass
z = w * x + b  # Weighted sum (linear part)
y_pred = torch.sigmoid(z)  # Predicted probability

# Compute binary cross-entropy loss
loss = binary_cross_entropy_loss(y_pred, y)

In [ ]:
loss

tensor(6.7012)

In [ ]:
# Derivatives:
# 1. dL/d(y_pred): Loss with respect to the prediction (y_pred)
dloss_dy_pred = (y_pred - y)/(y_pred*(1-y_pred))

# 2. dy_pred/dz: Prediction (y_pred) with respect to z (sigmoid derivative)
dy_pred_dz = y_pred * (1 - y_pred)

# 3. dz/dw and dz/db: z with respect to w and b
dz_dw = x  # dz/dw = x
dz_db = 1  # dz/db = 1 (bias contributes directly to z)

dL_dw = dloss_dy_pred * dy_pred_dz * dz_dw
dL_db = dloss_dy_pred * dy_pred_dz * dz_db

In [ ]:
print(f"Manual Gradient of loss w.r.t weight (dw): {dL_dw}")
print(f"Manual Gradient of loss w.r.t bias (db): {dL_db}")

Manual Gradient of loss w.r.t weight (dw): 6.691762447357178
Manual Gradient of loss w.r.t bias (db): 0.998770534992218


In [ ]:
#Now with Autograd
x = torch.tensor(6.7)
y = torch.tensor(0.0)

In [ ]:
w = torch.tensor(1.0, requires_grad=True)
b = torch.tensor(0.0, requires_grad=True)

In [ ]:
w

tensor(1., requires_grad=True)

In [ ]:
b

tensor(0., requires_grad=True)

In [ ]:
z = w*x + b
z

tensor(6.7000, grad_fn=<AddBackward0>)

In [ ]:
y_pred = torch.sigmoid(z)
y_pred

tensor(0.9988, grad_fn=<SigmoidBackward0>)

In [ ]:
loss = binary_cross_entropy_loss(y_pred, y)
loss

tensor(6.7012, grad_fn=<NegBackward0>)

In [ ]:
#To calculate backward derivative
loss.backward()

In [ ]:
w.grad

tensor(6.6918)

In [ ]:
b.grad

tensor(0.9988)

In [ ]:
#multiple inputs
x = torch.tensor([1.0,2.0,3.0], requires_grad=True)
x

tensor([1., 2., 3.], requires_grad=True)

In [ ]:
#y = x1^2 + x2^2 + x3^2 / 3
y=(x**2).mean()
y

tensor(4.6667, grad_fn=<MeanBackward0>)

In [ ]:
y.backward()

In [ ]:
x.grad
#getting three gradients, one for each
#dy/dx1 = 2x1/3, dy/dx2 = 2x2/3, dy/dx3 = 2x3/3

tensor([0.6667, 1.3333, 2.0000])

In [ ]:
#after calculating the grdient it should be cleared
#other wise it will be added to same gradient if code runs again
x.grad.zero_()

tensor([0., 0., 0.])

In [ ]:
#when we dont need to calculate the gradient we can use
# option 1 - requires_grad_(False)
# option 2 - detach()
# option 3 - torch.no_grad()

In [ ]:
x = torch.tensor([1.0,2.0,3.0], requires_grad=False)
x

tensor([1., 2., 3.])