<a href="https://colab.research.google.com/github/Jalaludin17/Pytorch/blob/main/03_Pytorch_Neuron_scratch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [ ]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [ ]:
df.shape

(569, 33)

In [ ]:
df.drop(columns=['id','Unnamed: 32'], inplace=True)
df.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

### Train Test Split

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

In [ ]:
#for standard scaling : same size or unit
scalar = StandardScaler()
X_train = scalar.fit_transform(X_train)
X_test = scalar.transform(X_test)

In [ ]:
X_train

array([[-0.81489744, -1.41805954, -0.78359195, ..., -0.39360406,
        -1.33562578, -0.89098058],
       [ 1.19646411, -0.16473253,  1.10428981, ...,  0.69434494,
         0.59526606, -0.79872855],
       [-0.49445293, -0.38207247, -0.43292619, ..., -0.58379207,
        -0.54158149,  0.65154528],
       ...,
       [-1.56136149, -1.16208138, -1.55282097, ..., -1.71327286,
        -0.47861762, -0.2536029 ],
       [ 1.03624185,  2.11733687,  1.05046862, ...,  1.30582776,
         0.18600094,  0.48141816],
       [ 0.13499165,  0.97267984,  0.08458526, ...,  0.36944681,
        -0.67975219, -0.85983054]])

In [ ]:
X_test

array([[ 0.27232502,  1.56432746,  0.25143095, ...,  0.62538072,
        -0.37017986,  0.69886938],
       [-0.26270288,  1.44599794, -0.32404178, ..., -0.79298356,
        -0.73746907, -0.88858442],
       [ 2.62129775,  1.78891207,  2.77274672, ...,  2.47515455,
         0.58127409,  0.2939189 ],
       ...,
       [-1.49927537, -1.1161985 , -1.37189896, ..., -0.97979999,
        -1.06977835,  1.53872229],
       [-1.38282812, -1.29490024, -1.32345989, ..., -0.60034348,
         1.42603927,  0.42570752],
       [ 0.57560286, -1.06307096,  0.51225672, ...,  0.01696298,
        -0.15330432, -0.75439965]])

In [ ]:
y_train

139    B
186    M
431    B
405    B
46     B
      ..
553    B
47     M
175    B
446    M
385    M
Name: diagnosis, Length: 455, dtype: object

In [ ]:
#encoder for output
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [ ]:
y_train

array([0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0,
       0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1,
       1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1,
       0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0,
       1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0,
       1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1,

In [ ]:
#numpy to pytorch tensors
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [ ]:
X_train_tensor

tensor([[-0.8149, -1.4181, -0.7836,  ..., -0.3936, -1.3356, -0.8910],
        [ 1.1965, -0.1647,  1.1043,  ...,  0.6943,  0.5953, -0.7987],
        [-0.4945, -0.3821, -0.4329,  ..., -0.5838, -0.5416,  0.6515],
        ...,
        [-1.5614, -1.1621, -1.5528,  ..., -1.7133, -0.4786, -0.2536],
        [ 1.0362,  2.1173,  1.0505,  ...,  1.3058,  0.1860,  0.4814],
        [ 0.1350,  0.9727,  0.0846,  ...,  0.3694, -0.6798, -0.8598]],
       dtype=torch.float64)

### Defining the model

In [ ]:
class MysimpleNN():
  def __init__(self, X): #constructor
    self.weights = torch.rand(X.shape[1],1, dtype=torch.float64, requires_grad=True) #shape[1], 1 is (31,1) second one is output for each row one output
    self.bias = torch.zeros(1, dtype=torch.float64, requires_grad=True)

  def forward(self, X):
    z = torch.matmul(X, self.weights) + self.bias
    return torch.sigmoid(z)

  def loss_function(self, y_pred, y):
    epsilon = 1e-7 #to prevent log(0)
    y_pred = torch.clamp(y_pred, epsilon, 1-epsilon) #keeps the y_pred between epsilon and 1-epsilon

  #calculate loss : binary cross entropy
    loss = -(y*torch.log(y_pred) + (1-y)*torch.log(1-y_pred))
    return loss.mean()

#### Important Parameters

In [ ]:
learning_rate = 0.1
epochs = 25

In [ ]:
#Training Model
model = MysimpleNN(X_train_tensor)

#define loops
for epoch in range(epochs):
  #forward pass
  y_pred = model.forward(X_train_tensor)

  #calculate loss
  loss = model.loss_function(y_pred, y_train_tensor)

  #backward pass
  loss.backward()

  #Parameters, weights update
  with torch.no_grad(): #turning off gradient tracking
    model.weights -= learning_rate * model.weights.grad
    model.bias -= learning_rate * model.bias.grad

  #parameters update
  model.weights.grad.zero_()
  model.bias.grad.zero_()

  #print loss in each epoch
  print(f"Epoch {epoch+1} loss: {loss.item()}")

Epoch 1 loss: 3.576194679859157
Epoch 2 loss: 3.4553329610145003
Epoch 3 loss: 3.332305277869159
Epoch 4 loss: 3.2047692314892986
Epoch 5 loss: 3.0759246788048094
Epoch 6 loss: 2.9430328651046422
Epoch 7 loss: 2.804729020991034
Epoch 8 loss: 2.6587244331667654
Epoch 9 loss: 2.513059503872699
Epoch 10 loss: 2.362174852640704
Epoch 11 loss: 2.2072421687003705
Epoch 12 loss: 2.049644532029759
Epoch 13 loss: 1.8973764152509884
Epoch 14 loss: 1.7452493266446234
Epoch 15 loss: 1.5957432034293375
Epoch 16 loss: 1.457022759409738
Epoch 17 loss: 1.3289729612958794
Epoch 18 loss: 1.2127468236461965
Epoch 19 loss: 1.1125558323845934
Epoch 20 loss: 1.0292387744031442
Epoch 21 loss: 0.9626460589588309
Epoch 22 loss: 0.9114892160859954
Epoch 23 loss: 0.873490223635781
Epoch 24 loss: 0.8457919909101371
Epoch 25 loss: 0.8255128996446883


In [ ]:
model.bias

tensor([-0.1500], dtype=torch.float64, requires_grad=True)

### Evaluation

In [ ]:
with torch.no_grad():
  y_pred = model.forward(X_test_tensor)
  y_pred = (y_pred > 0.5).float()

print(y_pred)

tensor([[1.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.],
        [0.],
        [1.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.],
      

In [ ]:
with torch.no_grad():
  y_pred = model.forward(X_test_tensor)
  y_pred = (y_pred > 0.5).float()
  accuracy= (y_pred == y_test_tensor).float().mean()
  print(f"Accuracy: {accuracy}")

Accuracy: 0.5138503909111023
