In [ ]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [ ]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [ ]:
df.drop(columns=['id','Unnamed: 32'], inplace=True)
df.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

###Train Test Split

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

In [ ]:
#for standard scaling : same size or unit
scalar = StandardScaler()
X_train = scalar.fit_transform(X_train)
X_test = scalar.transform(X_test)

In [ ]:
X_test

array([[ 0.36275946, -1.77129418,  0.41746843, ...,  1.02419781,
         0.5233315 ,  1.03728645],
       [ 0.60109045, -0.87655805,  0.50781413, ...,  0.30959986,
        -1.01113804, -0.65346085],
       [-0.36641986, -1.24995187, -0.30324385, ...,  0.61976578,
        -0.44325029,  2.02699219],
       ...,
       [-1.04169098,  0.85890126, -1.04654254, ..., -1.27848007,
        -1.13342655, -0.92032794],
       [-0.15362434, -0.90004194, -0.20345292, ..., -0.35147927,
        -0.62584547, -1.07762046],
       [ 1.09761333, -0.77088055,  1.14434063, ...,  1.44231364,
         1.41955552,  1.6146148 ]])

In [ ]:
y_train

398    B
330    M
93     B
204    B
545    B
      ..
131    M
34     M
255    M
547    B
308    B
Name: diagnosis, Length: 455, dtype: object

In [ ]:
#encoder for output
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [ ]:
y_train

array([0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1,
       0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0,
       0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1,
       0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1,
       1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0,
       0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0,
       1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1,
       0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [ ]:
#numpy to pytorch tensors
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [ ]:
X_train_tensor

tensor([[-0.8856, -1.0809, -0.9045,  ..., -0.9089, -0.5253,  0.4823],
        [ 0.5245, -0.9212,  0.5530,  ...,  1.2583,  0.1933,  0.4623],
        [-0.2075, -0.2660, -0.2355,  ..., -0.5508, -0.3779, -1.0228],
        ...,
        [-0.0628, -0.5595, -0.0371,  ...,  0.3354,  0.2754, -0.2252],
        [-1.1126, -0.6699, -1.0876,  ..., -0.4866, -0.3561,  0.6714],
        [-0.1933, -1.5787, -0.2729,  ..., -1.4176, -1.0664, -1.2650]],
       dtype=torch.float64)

### Model class

In [ ]:
import torch.nn as nn

class Model(nn.Module):
  def __init__(self, input_features):
    super().__init__()
    self.layers = nn.Sequential(
        nn.Linear(input_features, 3),
        nn.ReLU(),
        nn.Linear(3, 1),
        nn.Sigmoid()
    )

  def forward(self, features):
    out = self.layers(features)

    return out

  def loss_function(self, y_pred, y):
    epsilon = 1e-7 #to prevent log(0)
    y_pred = torch.clamp(y_pred, epsilon, 1-epsilon) #keeps the y_pred between epsilon and 1-epsilon


  #calculate loss : binary cross entropy
    loss = -(y*torch.log(y_pred) + (1-y)*torch.log(1-y_pred))
    return loss.mean()

In [ ]:
learning_rate = 0.1
epochs = 25

In [ ]:
#Training Model
model = Model(X_train_tensor.shape[1])

# Convert tensors to float32
X_train_tensor = X_train_tensor.float()
X_test_tensor = X_test_tensor.float()
y_train_tensor = y_train_tensor.float() # also convert target tensor

#define loops
for epoch in range(epochs):
  #forward pass
  y_pred = model(X_train_tensor)

  #calculate loss
  loss = model.loss_function(y_pred, y_train_tensor)

  #backward pass
  loss.backward()

  #Parameters, weights update
  with torch.no_grad(): #turning off gradient tracking
    model.layers[0].weight -= learning_rate * model.layers[0].weight.grad
    model.layers[0].bias -= learning_rate * model.layers[0].bias.grad

    model.layers[2].weight -= learning_rate * model.layers[2].weight.grad
    model.layers[2].bias -= learning_rate * model.layers[2].bias.grad

  #parameters update
  model.layers[0].weight.grad.zero_()
  model.layers[0].bias.grad.zero_()

  model.layers[2].weight.grad.zero_()
  model.layers[2].bias.grad.zero_()

  #print loss in each epoch
  print(f"Epoch {epoch+1} loss: {loss.item()}")

Epoch 1 loss: 0.7277107238769531
Epoch 2 loss: 0.7236518859863281
Epoch 3 loss: 0.7198766469955444
Epoch 4 loss: 0.7163596749305725
Epoch 5 loss: 0.7130867838859558
Epoch 6 loss: 0.7100421190261841
Epoch 7 loss: 0.7072059512138367
Epoch 8 loss: 0.7045648097991943
Epoch 9 loss: 0.7021073698997498
Epoch 10 loss: 0.6998230218887329
Epoch 11 loss: 0.6976980566978455
Epoch 12 loss: 0.6957225203514099
Epoch 13 loss: 0.693885862827301
Epoch 14 loss: 0.6921772956848145
Epoch 15 loss: 0.6905879378318787
Epoch 16 loss: 0.68911212682724
Epoch 17 loss: 0.6877427101135254
Epoch 18 loss: 0.6864725947380066
Epoch 19 loss: 0.6852923035621643
Epoch 20 loss: 0.6841951608657837
Epoch 21 loss: 0.6831761598587036
Epoch 22 loss: 0.68222975730896
Epoch 23 loss: 0.6813505291938782
Epoch 24 loss: 0.680533230304718
Epoch 25 loss: 0.6797723770141602


In [ ]:
model.layers[0].weight

Parameter containing:
tensor([[-0.0174, -0.1595, -0.0166,  0.0493,  0.1605,  0.0022, -0.0139, -0.0010,
         -0.0233, -0.0888, -0.1711,  0.1246,  0.1635, -0.1796, -0.0071,  0.1438,
         -0.0971, -0.0555, -0.1080,  0.0576,  0.0863,  0.1036,  0.0196,  0.0362,
          0.0217,  0.1125, -0.1564, -0.0014,  0.1403, -0.0283],
        [ 0.0073, -0.0636,  0.0621,  0.0018, -0.1221, -0.0051,  0.0970,  0.0514,
         -0.1320,  0.0751, -0.1136, -0.1652, -0.0124, -0.0969, -0.0979, -0.0108,
          0.1623, -0.0784,  0.1808, -0.0103,  0.0396, -0.0922, -0.1158, -0.1275,
          0.1567,  0.1104, -0.0482,  0.1358, -0.1828,  0.0484],
        [ 0.0385,  0.0773, -0.1667,  0.0586,  0.1172, -0.0857, -0.0780,  0.0730,
         -0.0280, -0.0740, -0.0881, -0.1591, -0.0961, -0.1964, -0.0511,  0.0576,
         -0.0647, -0.1608,  0.0645,  0.1616, -0.1378,  0.0160, -0.1158,  0.0324,
         -0.1625, -0.1471, -0.1525, -0.1411,  0.1509, -0.0673]],
       requires_grad=True)

In [ ]:
model.layers[0].bias

Parameter containing:
tensor([ 0.0700, -0.1791,  0.0289], requires_grad=True)

In [ ]:
model.layers[2].weight

Parameter containing:
tensor([[ 0.0971,  0.2361, -0.3595]], requires_grad=True)

In [ ]:
model.layers[2].bias

Parameter containing:
tensor([-0.0647], requires_grad=True)

### Evaluation

In [ ]:
with torch.no_grad():
  y_pred = model(X_test_tensor)
  y_pred = (y_pred > 0.5).float()

  print(y_pred)

tensor([[1.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
      

In [ ]:
with torch.no_grad():
  y_pred = model(X_test_tensor)
  y_pred = (y_pred > 0.5).float()
  accuracy= (y_pred == y_test_tensor).float().mean()
  print(f"Accuracy: {accuracy}")

Accuracy: 0.6108033061027527
