### Neural Network Module

#### 1.Single Neuron

In [ ]:
#create a nn module
import torch
import torch.nn as nn

class Model(nn.Module):
  def __init__(self, num_features):
    super().__init__()
    self.linear = nn.Linear(num_features, 1) #num_features are inputs and 1 is output
    self.sigmoid = nn.Sigmoid()

  def forward(self, features):
    out = self.linear(features)
    out = self.sigmoid(out)
    return out

In [ ]:
#creating dataset
features = torch.randn(100, 5) #100 rows 5 columns
print(features)

tensor([[-0.2434,  1.1194, -0.3771, -2.0442,  0.6770],
        [-0.5440, -2.3643, -0.9850, -0.7293,  0.8669],
        [-0.5560, -0.8691,  0.1689, -1.9503, -0.3761],
        [-2.1256,  1.2495,  1.8104,  0.1716, -2.0455],
        [-0.4489, -0.0179, -0.1142, -0.2903,  1.2891],
        [-1.1490,  1.2864, -0.8236,  0.5846,  0.1802],
        [ 2.2947, -0.2728,  0.0826,  0.4602,  0.6255],
        [-0.5154,  0.3959, -0.5968, -0.2571,  0.9366],
        [ 1.5340, -1.2606, -0.5182, -0.1256, -0.0544],
        [-0.4564,  0.2984, -0.5090, -1.1170,  0.3191],
        [-1.2930,  0.0455, -0.5305,  0.0653,  0.1923],
        [ 1.2697,  0.6807,  1.6694,  0.1804,  1.4620],
        [ 1.7530,  0.3759, -0.4021, -0.7814, -2.0510],
        [ 0.2663, -1.4256, -0.8499,  0.5359, -0.2523],
        [-0.1954,  0.0594, -0.1468,  0.8903, -0.4181],
        [ 2.5876, -1.3824,  0.9345, -0.0767, -0.6955],
        [ 0.5318,  0.3644,  1.1838, -0.7832,  1.5310],
        [ 0.9449, -0.6284,  1.1958, -0.0909, -0.2398],
        [-

In [ ]:
features.shape[1]

5

In [ ]:
#train model
model = Model(features.shape[1]) #5 no of columns

#run forward pass
model(features)

tensor([[0.1951],
        [0.5939],
        [0.2733],
        [0.1421],
        [0.4748],
        [0.2780],
        [0.6743],
        [0.3872],
        [0.5972],
        [0.2806],
        [0.3435],
        [0.6235],
        [0.2387],
        [0.5714],
        [0.4374],
        [0.6613],
        [0.5134],
        [0.5416],
        [0.3327],
        [0.5899],
        [0.3362],
        [0.5311],
        [0.3025],
        [0.4589],
        [0.4870],
        [0.6093],
        [0.3383],
        [0.6961],
        [0.5440],
        [0.3092],
        [0.3291],
        [0.5662],
        [0.5912],
        [0.2672],
        [0.2897],
        [0.4930],
        [0.4894],
        [0.2505],
        [0.3010],
        [0.4444],
        [0.5251],
        [0.5517],
        [0.5829],
        [0.2424],
        [0.4514],
        [0.6025],
        [0.7776],
        [0.7080],
        [0.4387],
        [0.4075],
        [0.2130],
        [0.6358],
        [0.5733],
        [0.4284],
        [0.3282],
        [0

In [ ]:
model.linear.weight

Parameter containing:
tensor([[ 0.2410, -0.3980,  0.1289,  0.3749,  0.3629]], requires_grad=True)

In [ ]:
model.linear.bias

Parameter containing:
tensor([-0.3439], requires_grad=True)

In [ ]:
#for model Visualization
!pip install torchinfo

In [ ]:
from torchinfo import summary
summary(model, input_size=(100, 5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [100, 1]                  --
├─Linear: 1-1                            [100, 1]                  6
├─Sigmoid: 1-2                           [100, 1]                  --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

#### 2.Multi Layer Perceptron

In [ ]:
class Model(nn.Module):
  def __init__(self, num_features):
    super().__init__()
    self.linear1= nn.Linear(num_features, 3)
    self.relu = nn.ReLU()
    self.linear2 = nn.Linear(3, 1)
    self.sigmoid = nn.Sigmoid()

  def forward(self, features):
    out = self.linear1(features)
    out = self.relu(out)
    out = self.linear2(out)
    out = self.sigmoid(out)
    return out

In [ ]:
#creating dataset
features = torch.randn(10, 5)

In [ ]:
model = Model(features.shape[1])

#Run forward pass
model(features)

tensor([[0.4906],
        [0.5253],
        [0.4971],
        [0.4747],
        [0.5282],
        [0.4971],
        [0.4747],
        [0.5221],
        [0.5495],
        [0.4853]], grad_fn=<SigmoidBackward0>)

In [ ]:
model.linear1.weight

Parameter containing:
tensor([[-0.1590, -0.1443,  0.1156,  0.1254, -0.3996],
        [ 0.2192,  0.1736,  0.3099,  0.1351,  0.0796],
        [ 0.3431, -0.2841,  0.3041,  0.2271, -0.4121]], requires_grad=True)

In [ ]:
model.linear1.bias

Parameter containing:
tensor([-0.4082,  0.2133,  0.1413], requires_grad=True)

In [ ]:
summary(model, input_size=(10, 5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 3]                   18
├─ReLU: 1-2                              [10, 3]                   --
├─Linear: 1-3                            [10, 1]                   4
├─Sigmoid: 1-4                           [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

#### Sequention Containers

In [ ]:
class Model(nn.Module):
  def __init__(self, num_features):
    super().__init__()
    self.network=nn.Sequential(
        nn.Linear(num_features, 3),
        nn.ReLU(),
        nn.Linear(3,1),
        nn.Sigmoid()
    )

  def forward(self, features):
    out = self.network(features)

    return out

In [ ]:
features = torch.randn(10, 5)

In [ ]:
model = Model(features.shape[1])

model(features) #one output for each row of the sample

tensor([[0.4503],
        [0.4974],
        [0.4794],
        [0.5309],
        [0.4853],
        [0.4897],
        [0.4218],
        [0.4130],
        [0.5167],
        [0.4865]], grad_fn=<SigmoidBackward0>)

### New Training Pipeline

In [ ]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [ ]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [ ]:
df.drop(columns=['id','Unnamed: 32'], inplace=True)
df.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

In [ ]:
#for standard scaling : same size or unit
scalar = StandardScaler()
X_train = scalar.fit_transform(X_train)
X_test = scalar.transform(X_test)

In [ ]:
y_train

130    B
524    B
39     M
364    B
105    M
      ..
463    B
141    M
308    B
108    M
261    M
Name: diagnosis, Length: 455, dtype: object

In [ ]:
#encoder for output
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [ ]:
#numpy to pytorch tensors
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [ ]:
X_train_tensor.to(torch.float32)
X_test_tensor.to(torch.float32)
y_train_tensor.to(torch.float32)
y_test_tensor.to(torch.float32)

tensor([1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.,
        1., 0., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 1., 1., 0., 0., 0.,
        1., 0., 1., 0., 0., 0., 1., 0., 0., 0., 0., 1., 1., 0., 0., 1., 0., 0.,
        0., 0., 0., 0., 0., 1., 1., 1., 0., 1., 0., 1., 1., 0., 1., 0., 0., 0.,
        0., 0., 0., 0., 1., 1., 1., 0., 0., 0., 0., 1., 1., 0., 0., 0., 1., 1.,
        0., 1., 0., 1., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.,
        1., 1., 1., 1., 0., 0.])

#### 1. Single neuron model 2 (nn modul)

In [ ]:
import torch
import torch.nn as nn

class Model(nn.Module):
  def __init__(self, num_features):
    super().__init__()
    self.linear = nn.Linear(num_features, 1) #num_features are inputs and 1 is output
    self.sigmoid = nn.Sigmoid()

  def forward(self, features):
    out = self.linear(features)
    out = self.sigmoid(out)
    return out

  def loss_function(self, y_pred, y):
    epsilon = 1e-7 #to prevent log(0)
    y_pred = torch.clamp(y_pred, epsilon, 1-epsilon) #keeps the y_pred between epsilon and 1-epsilon


  #calculate loss : binary cross entropy
    loss = -(y*torch.log(y_pred) + (1-y)*torch.log(1-y_pred))
    return loss.mean()

In [ ]:
learning_rate = 0.1
epochs = 25

In [ ]:
#creat model
model = Model(X_train_tensor.shape[1])

for epoch in range(epochs):
  # Forward pass
  y_pred = model(X_train_tensor)

  loss = model.loss_function(y_pred, y_train_tensor)

  # Backward pass
  loss.backward()

  # Parameters update
  with torch.no_grad():
    model.linear.weight -= learning_rate * model.linear.weight.grad
    model.linear.bias -= learning_rate * model.linear.bias.grad

  # Zero gradients
  model.linear.weight.grad.zero_()
  model.linear.bias.grad.zero_()

  # print loss for monitoring
  print(f"epoch: {epoch}, loss: {loss.item()}")

epoch: 0, loss: 0.750129222869873
epoch: 1, loss: 0.7357900142669678
epoch: 2, loss: 0.7262836694717407
epoch: 3, loss: 0.7196742296218872
epoch: 4, loss: 0.7147650718688965
epoch: 5, loss: 0.7108646035194397
epoch: 6, loss: 0.7075890302658081
epoch: 7, loss: 0.704728901386261
epoch: 8, loss: 0.702168345451355
epoch: 9, loss: 0.6998417973518372
epoch: 10, loss: 0.6977089047431946
epoch: 11, loss: 0.6957435607910156
epoch: 12, loss: 0.6939266324043274
epoch: 13, loss: 0.6922433376312256
epoch: 14, loss: 0.6906811594963074
epoch: 15, loss: 0.6892295479774475
epoch: 16, loss: 0.6878790855407715
epoch: 17, loss: 0.6866213083267212
epoch: 18, loss: 0.6854487061500549
epoch: 19, loss: 0.684354305267334
epoch: 20, loss: 0.6833318471908569
epoch: 21, loss: 0.6823756694793701
epoch: 22, loss: 0.6814805269241333
epoch: 23, loss: 0.680641770362854
epoch: 24, loss: 0.6798551082611084


In [ ]:
model.linear.weight

Parameter containing:
tensor([[ 0.0889, -0.0828,  0.1239, -0.0818,  0.1097,  0.0215, -0.0377, -0.1789,
          0.0032, -0.0139,  0.0610, -0.0961,  0.0415, -0.0276, -0.0494,  0.1154,
          0.0179, -0.1109,  0.1196,  0.0711,  0.1209,  0.0735,  0.0422, -0.0563,
          0.0163,  0.0383, -0.1313, -0.0602, -0.1249,  0.0383]],
       requires_grad=True)

In [ ]:
#Evaluation
with torch.no_grad():
  X_test_tensor = X_test_tensor.float() # Cast X_test_tensor to float32
  y_pred = model(X_test_tensor)
  y_pred = (y_pred > 0.5).float() # Changed threshold to 0.5 for binary classification
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f"Accuracy: {accuracy}")

Accuracy: 0.6246537566184998


#### 2. Single neuron model 3 (Built in loss function)

In [ ]:
import torch
import torch.nn as nn

class Model2(nn.Module):
  def __init__(self, num_features):
    super().__init__()
    self.linear = nn.Linear(num_features, 1) #num_features are inputs and 1 is output
    self.sigmoid = nn.Sigmoid()

  def forward(self, features):
    out = self.linear(features)
    out = self.sigmoid(out)
    return out

In [ ]:
learning_rate = 0.1
epochs = 25
loss_function = nn.BCELoss()

In [ ]:
#creat model
model = Model2(X_train_tensor.shape[1])

for epoch in range(epochs):
  # Forward pass
  y_pred = model(X_train_tensor)

  # Reshape y_train_tensor to match y_pred
  #loss = loss_function(y_pred, y_train_tensor.unsqueeze(1))
  loss = loss_function(y_pred, y_train_tensor.view(-1,1))

  # Backward pass
  loss.backward()

  # Parameters update
  with torch.no_grad():
    model.linear.weight -= learning_rate * model.linear.weight.grad
    model.linear.bias -= learning_rate * model.linear.bias.grad

  # Zero gradients
  model.linear.weight.grad.zero_()
  model.linear.bias.grad.zero_()

  # print loss for monitoring
  print(f"epoch: {epoch}, loss: {loss.item()}")

epoch: 0, loss: 0.9039607644081116
epoch: 1, loss: 0.6620848178863525
epoch: 2, loss: 0.5274604558944702
epoch: 3, loss: 0.4492189586162567
epoch: 4, loss: 0.39828696846961975
epoch: 5, loss: 0.3620578646659851
epoch: 6, loss: 0.33458712697029114
epoch: 7, loss: 0.3127971887588501
epoch: 8, loss: 0.29494917392730713
epoch: 9, loss: 0.27997925877571106
epoch: 10, loss: 0.2671930193901062
epoch: 11, loss: 0.25611358880996704
epoch: 12, loss: 0.24639983475208282
epoch: 13, loss: 0.2378000169992447
epoch: 14, loss: 0.23012301325798035
epoch: 15, loss: 0.22322075068950653
epoch: 16, loss: 0.2169761061668396
epoch: 17, loss: 0.2112952023744583
epoch: 18, loss: 0.20610150694847107
epoch: 19, loss: 0.20133216679096222
epoch: 20, loss: 0.19693471491336823
epoch: 21, loss: 0.192865252494812
epoch: 22, loss: 0.18908661603927612
epoch: 23, loss: 0.18556705117225647
epoch: 24, loss: 0.18227936327457428


In [ ]:
model.linear.weight

Parameter containing:
tensor([[ 0.2726,  0.1048,  0.1936,  0.2198, -0.0622,  0.1439,  0.2541,  0.1494,
          0.2036, -0.0365,  0.1253, -0.0216,  0.1428,  0.3207, -0.1056,  0.0821,
         -0.1392,  0.1102, -0.1964, -0.0223,  0.2364,  0.3486,  0.1643,  0.1568,
          0.1914,  0.2360,  0.1759,  0.3408,  0.1785,  0.0203]],
       requires_grad=True)

In [ ]:
#Evaluation
with torch.no_grad():
  X_test_tensor = X_test_tensor.float() # Cast X_test_tensor to float32
  y_pred = model(X_test_tensor)
  y_pred = (y_pred > 0.5).float() # Changed threshold to 0.5 for binary classification
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f"Accuracy: {accuracy}")

Accuracy: 0.5526315569877625


#### 3. Single neuron model 4 (Builtin Optimizer)

In [ ]:
import torch
import torch.nn as nn

class Model2(nn.Module):
  def __init__(self, num_features):
    super().__init__()
    self.linear = nn.Linear(num_features, 1) #num_features are inputs and 1 is output
    self.sigmoid = nn.Sigmoid()

  def forward(self, features):
    out = self.linear(features)
    out = self.sigmoid(out)
    return out

In [ ]:
learning_rate = 0.1
epochs = 25
loss_function = nn.BCELoss()

In [ ]:
#creat model
model = Model2(X_train_tensor.shape[1])

#optimizer
optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)

for epoch in range(epochs):

  # Forward pass
  y_pred = model(X_train_tensor)

  # Reshape y_train_tensor to match y_pred
  #loss = loss_function(y_pred, y_train_tensor.unsqueeze(1))
  loss = loss_function(y_pred, y_train_tensor.view(-1,1))

  #clear gradients
  optimizer.zero_grad()

  # Backward pass
  loss.backward()

  # Parameters update
  optimizer.step()

  # print loss for monitoring
  print(f"epoch: {epoch}, loss: {loss.item()}")

epoch: 0, loss: 0.5744136571884155
epoch: 1, loss: 0.45630037784576416
epoch: 2, loss: 0.39041265845298767
epoch: 3, loss: 0.34810709953308105
epoch: 4, loss: 0.31821581721305847
epoch: 5, loss: 0.29571807384490967
epoch: 6, loss: 0.27801766991615295
epoch: 7, loss: 0.2636273503303528
epoch: 8, loss: 0.2516290247440338
epoch: 9, loss: 0.24142305552959442
epoch: 10, loss: 0.2325999140739441
epoch: 11, loss: 0.22486984729766846
epoch: 12, loss: 0.218021422624588
epoch: 13, loss: 0.21189649403095245
epoch: 14, loss: 0.2063741534948349
epoch: 15, loss: 0.20136024057865143
epoch: 16, loss: 0.19678014516830444
epoch: 17, loss: 0.19257386028766632
epoch: 18, loss: 0.1886925846338272
epoch: 19, loss: 0.18509602546691895
epoch: 20, loss: 0.18175072968006134
epoch: 21, loss: 0.17862845957279205
epoch: 22, loss: 0.17570535838603973
epoch: 23, loss: 0.17296102643013
epoch: 24, loss: 0.17037789523601532
